version: '3'

services:
  # mysql_db:
  #   image: mysql:latest
  #   hostname: mysql_db
  #   command:
  #     - --character-set-server=utf8mb4
  #     - --collation-server=utf8mb4_unicode_ci
  #   restart: always
  #   volumes:
  #     - ./mysql/db:/var/lib/mysql
  #   ports:
  #     - "33061:3306"
  #   cap_add:
  #     - SYS_NICE
  #   environment:
  #     MYSQL_DATABASE: maskon
  #     MYSQL_USER: mask
  #     MYSQL_PASSWORD: root
  #     MYSQL_ROOT_PASSWORD: rootpassword

  backend:
    container_name: maskon_web
    build: ./back/django
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./back/django:/code
    expose:
      - "8000"
    ports:
      - "8000:8000"
    # links:
    #   - mysql_db:mysql_db
    # depends_on:
    #   - mysql_db

  migration:
      build: ./back/django
      image: app
      command: sh -c "python manage.py migrate"
      volumes:
          - ./back/django:/code
      # links:
      #     - mysql_db
      depends_on:
          - make_migrations
  
  make_migrations:
      build: ./back/django
      image: app
      command: sh -c "python manage.py makemigrations"
      volumes:
          - ./back/django:/code
      # links:
      #     - mysql_db
      # depends_on:
      #     - mysql_db
  # frontend:
  #   build: ./front/kakao
  #   container_name: kakao-con
  #   volumes:
  #     - build_folder:/frontend/build
  #   command: npm run start
  #   expose:
  #     - "3000"
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./build:/var/www/frontend
    depends_on:
      - backend
      # - frontend
volumes:
  build_folder: