version: '3'

services:
  mysql_db:
    image: mysql:latest
    restart: always
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234

  backend:
    container_name: maskon_web
    build: ./back/django
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./back/django:/code
    expose:
      - "8000"
    ports:
      - "8000:8000"
    links:
      - mysql_db:mysql_db
    depends_on:
      - mysql_db
  # frontend:
  #   build: ./front/kakao
  #   container_name: kakao-con
  #   volumes:
  #     - build_folder:/frontend/build
  #   command: npm run start
  #   expose:
  #     - "3000"
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./build:/var/www/frontend
    depends_on:
      - backend
      # - frontend
volumes:
  build_folder: