# Generated by Django 3.1.5 on 2021-01-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=140)),
                ('max_capacity', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('current', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.log')),
            ],
        ),
    ]
