# Generated by Django 3.1.5 on 2021-01-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AverageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.TimeField()),
                ('average_masked', models.IntegerField()),
                ('average_unmasked', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('masked', models.IntegerField()),
                ('unmasked', models.IntegerField()),
                ('average', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.averagelog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
