# Generated by Django 3.1.5 on 2021-01-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('log_id', models.IntegerField()),
                ('masked', models.IntegerField()),
                ('unmasked', models.IntegerField()),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='sensor.sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
