# Generated by Django 3.1.5 on 2021-01-19 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
        ('log', '0002_auto_20210119_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagelog',
            name='sensor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sensor.sensor'),
        ),
    ]
