# Generated by Django 3.1.5 on 2021-01-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20210119_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagelog',
            name='created_time',
            field=models.TimeField(),
        ),
    ]
